version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3100:8080"  # Host:Container
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - openwebui_data:/app/backend/data
    restart: unless-stopped

  model-init:
    image: curlimages/curl:latest
    container_name: model-init
    depends_on:
      - ollama
    entrypoint: >
      sh -c "
      echo 'Waiting for Ollama to be ready...' &&
      until curl -s http://ollama:11434; do sleep 2; done &&
      echo 'Pulling gpt-oss:20b model...' &&
      curl -X POST http://ollama:11434/api/pull -d '{"name": "gpt-oss:20b"}' &&
      echo 'Model pull initiated.'
      "
    restart: "no"

volumes:
  ollama_data:
  openwebui_data:
